on: [pull_request]

name: ChatGPT CodeReview

jobs:
  chatgpt_comment:
    runs-on: ubuntu-latest
    name: Let chatgpt comment on your PR.
    steps:
      - name: ChatGPT Integration - Open AI Key
        uses: adonaipinheirosmiles/chatgpt-action@v0.7
        id: chatgpt
        with:
          number: ${{ github.event.pull_request.number }}
          apiKey: ${{ secrets.OPENAI_API_KEY }}
          split: 'yolo'  # Use true to enable the unstable split feature.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}