on: [pull_request]

name: ChatGPT CodeReview

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CHATGPT_SESSION_TOKEN: ${{ secrets.CHATGPT_SESSION_TOKEN }}

jobs:
  chatgpt_comment:
    runs-on: ubuntu-latest
    name: Let chatgpt comment on your PR.
    steps:
      - name: ChatGPT comment
        uses: kxxt/chatgpt-action@v0.3
        id: chatgpt
        with:
          number: ${{ github.event.pull_request.number }}
          sessionToken: "$CHATGPT_SESSION_TOKEN"
          split: 'yolo'  # Use true to enable the unstable split feature.
        